version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "vk_chats"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1"
    ports:
      - "5432:5432"

  bot:
    build: ./app
    expose:
      - "8000"
    depends_on:
      - postgres
    restart: always